apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: auth-ms
  name: auth-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-ms
  template:
    metadata:
      labels:
        app: auth-ms
    spec:
      imagePullSecrets:
        - name: gcr-json-key
      containers:
        - name: auth-ms
          image: southamerica-east1-docker.pkg.dev/microservicios-474900/image-registry/auth-ms
          env:
            - name: PORT
              value: "3000"
            - name: NATS_SERVERS
              value: "nats://nats"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: auths-secrets
                  key: DATABASE_URL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: auths-secrets
                  key: JWT_SECRET
          resources: {}
